/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface ElectricButton {
        "lightTheme": boolean;
        "link": string;
    }
}
declare global {
    interface HTMLElectricButtonElement extends Components.ElectricButton, HTMLStencilElement {
    }
    var HTMLElectricButtonElement: {
        prototype: HTMLElectricButtonElement;
        new (): HTMLElectricButtonElement;
    };
    interface HTMLElementTagNameMap {
        "electric-button": HTMLElectricButtonElement;
    }
}
declare namespace LocalJSX {
    interface ElectricButton {
        "lightTheme"?: boolean;
        "link"?: string;
    }
    interface IntrinsicElements {
        "electric-button": ElectricButton;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "electric-button": LocalJSX.ElectricButton & JSXBase.HTMLAttributes<HTMLElectricButtonElement>;
        }
    }
}
